name: Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          pytest --alluredir=APS/TriCalc/src/report/allure-report APS/TriCalc/src/services/test/test_triangle_cal.py

  deploy:
    name: Deploy Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure Report files
        run: |
          mkdir -p gh-pages/APS/TriCalc/src/report
          cp -R APS/TriCalc/src/report/allure-report/* gh-pages/APS/TriCalc/src/report/
          
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
